Remove  shard related code
radixdlt/radixdlt-java pull request #260
Opened 2020-06-17 08:56 UTC by motoras

For details see [ticket](https://radixdlt.atlassian.net/browse/RPNV1-309)

2020-06-18 03:49 UTC, talekhinezh commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				ImmutableList.of(particleGroup),
Some funky tabs

2020-06-18 04:00 UTC, talekhinezh commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +		return AID.from(getHash().toByteArray());
Like mentioned in other library, this change I think would require some synchronization with the javascript library

2020-06-18 04:01 UTC, talekhinezh commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> -							.forEach(a -> {
Why the removal of tabs here?

2020-06-18 08:37 UTC, clstrfsck requested changes
Mostly good, but need to turn off automatic code reformatting on save.

Please fix up the unnecessary whitespace changes and remove commented out code.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				);
Most of these edits here look like a reformat without any other changes.  Please revert.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				ImmutableList.copyOf(particleGroups),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				ImmutableList.copyOf(particleGroups),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +			ImmutableList<ParticleGroup> particleGroups,
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				this.particleGroups,
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				.map(SpunParticle<Particle>::getParticle)
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +		return AID.from(getHash().toByteArray());
Right, this is planned.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +		.forEach(p -> {
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +						//					if (!e.getKey().getShardables().contains(address)) {
Commented out code should be removed.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/network/actions/FetchAtomsRequestAction.java
> +	//	@Override
Commented out code should be removed.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +
Extra blank line.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +								s.getSpin(),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +							&& nextUpdate.getType() != lastUpdate.getType();
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +					.filter(e -> e.getValue().isStore() && e.getKey().addresses().anyMatch(address::equals))
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +						if (stagedUuid != null && stagedParticleIndex.getOrDefault(stagedUuid, Collections.emptyMap()).get(e.getKey()) == Spin.DOWN) {
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +						Set<Atom> uppingAtoms = spinParticleIndex.getOrDefault(Spin.UP, Collections.emptySet());
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +				.filter(e -> e.getValue() == Spin.UP)
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> +				.filter(e -> e.getValue().isStore() && e.getKey().addresses().anyMatch(address::equals))
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/network/RadixNodeState.java
> +			RadixUniverseConfig universeConfig) {
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/network/actions/FetchAtomsRequestAction.java
> +			String uuid,
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/network/epics/FindANodeEpic.java
> +				.collect(Collectors.toMap(
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/network/epics/FindANodeEpic.java
> +				.filter(entry -> entry.getValue().getStatus().equals(WebSocketStatus.CONNECTED))
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/main/java/com/radixdlt/client/core/network/epics/FindANodeEpic.java
> +				.flatMap(a -> {
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				Observable.<RadixNodeAction>just(request).concatWith(Observable.never()),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				i -> {
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +					RadixNode peer = mock(RadixNode.class);
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				Observable.<RadixNodeAction>just(request).concatWith(Observable.never()),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				badPeer, mockedNodeState(WebSocketStatus.DISCONNECTED),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				Observable.<RadixNodeAction>just(request).concatWith(Observable.never()),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						)));
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						)));
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				badPeer, mockedNodeState(WebSocketStatus.DISCONNECTED),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				Observable.<RadixNodeAction>just(request).concatWith(Observable.never()),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						badPeer, mockedNodeState(WebSocketStatus.FAILED),
Unwanted whitespace changes.

2020-06-18 08:37 UTC, clstrfsck commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						badPeer, mockedNodeState(WebSocketStatus.FAILED),
Unwanted whitespace changes.

2020-06-26 06:51 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				);
Fixed

2020-06-26 06:51 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				ImmutableList.copyOf(particleGroups),
Fixed

2020-06-26 06:51 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +			ImmutableList<ParticleGroup> particleGroups,
Fixed

2020-06-26 06:51 UTC, motoras commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						)));
Fixed

2020-06-26 06:51 UTC, motoras commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				Observable.<RadixNodeAction>just(request).concatWith(Observable.never()),
Fixed

2020-06-26 06:51 UTC, motoras commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						badPeer, mockedNodeState(WebSocketStatus.FAILED),
Fixed

2020-06-26 07:14 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				ImmutableList.of(particleGroup),
Fixed

2020-06-26 07:15 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/ledger/InMemoryAtomStore.java
> -							.forEach(a -> {
Fixed

2020-06-26 07:15 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +				ImmutableList.copyOf(particleGroups),
Fixed

2020-06-26 07:15 UTC, motoras commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +						badPeer, mockedNodeState(WebSocketStatus.FAILED),
Fixed

2020-06-26 07:15 UTC, motoras commented on radixdlt-java/src/test/java/com/radixdlt/client/core/network/epics/FindANodeEpicTest.java
> +				badPeer, mockedNodeState(WebSocketStatus.DISCONNECTED),
Fixed

2020-06-26 07:17 UTC, motoras commented on radixdlt-java/src/main/java/com/radixdlt/client/core/atoms/Atom.java
> +
Fixed

2020-07-01 08:09 UTC, clstrfsck approved these changes

2020-07-01 08:26 UTC, merged